version: "3.7"

services:
  server:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.itsoup-assets-active-directory.entrypoints=http"
      - "traefik.http.routers.itsoup-assets-active-directory.rule=Host(`assets-active-directory.itsoup.test`)"
      - "traefik.http.services.itsoup-assets-active-directory.loadbalancer.healthcheck.path=/health-check"
      - "traefik.http.services.itsoup-assets-active-directory.loadbalancer.healthcheck.interval=60s"
    networks:
      - web

  db:
    ports:
      - 33062:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: asset_active_directory
    networks:
      - maintenance

networks:
  web:
    external: true
  maintenance:
    external: true
